### ISSUE TITLE
Meta issue: UX improvement

### ISSUE THREAD

**Issue by ShGKme** [nextcloud/talk-desktop#10]
Talk Web works only on webpage and online. A desktop app may be opened offline and stay open for a long time. 

- [ ] Work offline - show offline badge (and reload on connect?)
- [x] Stop reloading the page on errors
- [x] Fix disconnect on long stay
- [ ] Handle capabilities updates

**Comment by Areopagitics** [comment]
I'm looking forward to it working completely offline ... this is the one thing that still makes Signal more useful.
