### ISSUE TITLE
Meta issue: Fix Nextcloud apps integrations

### ISSUE THREAD

**Issue by ShGKme** [nextcloud/talk-desktop#4]
Add talk integration with other Nextcloud apps:

- [x] Files: Open received files
  - [x] In the beginning - open all files in the default Web-Browser or Web View
  - [x] Open in the default Web-Browser or Web View
    - [x] Documents (Office)
    - [x] Contacts
    - [x] Other files
  - [x] #255
    - [x] Images
    - [x] Videos
  - [x] #256 
    - [x] PDFs
    - [x] MDs (texts)
- [x] Files: Send files from Nextcloud (related: https://github.com/nextcloud/nextcloud-dialogs/issues/1)
- [x] User profile - open in the default Web-Browser
- [x] #31
    - [x] ⚠️ Add empty no-op icon quickly so it does not block screencasts
    - [x] Implement notifications afterwards
- [x] #26
    - [x] ⚠️ Add empty no-op icon quickly so it does not block screencasts
    - [ ] Implement status afterwards
- [ ] #30
    - [x] ⚠️ Add empty no-op icon quickly so it does not block screencasts
    - [ ] Implement search afterwards
