### ISSUE TITLE
🛣️  Roadmap for v1.0.0 

### ISSUE THREAD

**Issue by ShGKme** [nextcloud/talk-desktop#635]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

# 🛣️ Roadmap for v1.0.0

## 🐞 Critical issues

- Check after distribution is done:
  - [x] #588
  - [ ] #50

## 🐣 Basic features

- [x] User Status #26
- [ ] Do not play sound on system DnD
- [x] Do not play sound on user DnD #415
- [ ] Logging + Crash Reports #54
- [ ] Custom SSL on Linux #23, also related #459
- [ ] Client isn't using the notification action link in native system notifications #376
  - [ ] Add support for `#direct-call` links https://github.com/nextcloud/talk-desktop/issues/631
- [ ] Better talk-hash handle #389
- [x] Better handle global styles: https://github.com/nextcloud/talk-desktop/pull/741

## ⚙️ Settings #27

- [x] #812
- [x] DnD settings #632
- [x] Light/Dark Theme #17
- [ ] Run on Startup #29, #99

## 🔐 Security improvements

- [ ] #9
- [ ] #18
- [ ] #320

## 🔔 Improved notifications

- [x] https://github.com/nextcloud/talk-desktop/pull/640
- [ ] Add a popup window for a call notification with join/decline buttons #292
- [ ] Make `notifications` app reusable as a library
- [ ] On Talk side - add frontend API to get unread conversations count
  - [ ] Unread counter on icon #85, #391
  - [ ] Unread dot or counter on the tray icon #291, #391  
  - [ ] Check also: #290, #378

## ⛓️ Integrations

- [x] https://github.com/nextcloud/talk-desktop/pull/784
- [x] https://github.com/nextcloud/talk-desktop/pull/785

## 🚀 Prepare production releases

- [x] #816
  - [x] #842
  - [x] #843
  - [x] #848
- [x] #42
- [ ] #166
  - [ ] Windows
  - [ ] Mac
  - [ ] Linux
- [ ] #817
- [ ] Publish releases
- [ ] Add beta releases workflow

---

## 👀 Nice to have

- [x] Monochrome icon settings #364
- [ ] Save and restore window position #15
- [ ] Add support for user high-contrast themes and dyslexia font #56
- [ ] Add log in via web-browser #61
- [ ] System-wide push to talk #170
- [ ] Complete Multi-account support #7
- [ ] #813
  - [ ] Fix issues with non-primary windows #294
- [ ] Search messages #30
- [ ] #814
- [ ] Screensharing notice #596
- [ ] Integrations
  - [ ] Widgets
  - [ ] Smart Link picker #62
  - [ ] #815

**Comment by NikoKS** [comment]
@ShGKme Congratulations on v1.0 release! Really great work you did with the desktop client 🎉

**Comment by nickvergessen** [comment]
v1.0.0 is out 🎉 
So I'm closing this to avoid confusion.
We are aware that not all things are solved yet and will re-prioritize the existing items after the developer had a well deserved break.

**Comment by thomas-mc-work** [comment]
TBW: This issue is still pinned. You might also want to remove that (to avoid confusion 😉 )
